### ISSUE TITLE
Downloads not worked with SEO-URL under /download/2 ect.

### ISSUE THREAD

**Issue by AlexL777** [PHPBoost/PHPBoost#106] opened 2017-08-25 07:29 UTC
Hello Developers,

I have unfortunately a Problem with the downloads with PHPBoost 5.1 and a completely fresh installation.

From the beginning, a testcategory is created in the downloads and I have uploaded a ZIP file with the name `de-DE.zip` as an example. This is then linked to `/upload/de-DE.zip`

Unfortunately it shows me in the frontend that the download page or the download can not be found.

Look here >> https://phpboost.wpzweinull.ch/download/download/1

SEO URLs are enabled and the complete .htaccess is also in the root directory.

How can I fix the problem or do you notice it?

Thanks in Advance.

**Comment by ElenWii** [comment] 2017-08-25 08:13
hi AlexL777
I just opened a ticket on this subject in the bugtracker (https://www.phpboost.com/bugtracker/detail/1815-download-lien-mort-avec-upload)
We will look for this problem next week when the main developper back from holidays.
Sorry for the inconvenience.
PHPBoost Team

**Comment by AlexL777** [comment] 2017-08-25 08:18
Hi,

OK thank you. So much patience I have and will wait.

**Comment by janus57** [comment] 2017-08-25 10:11
Hello,

is it possible to give us the system report ? (Administration panel -> Tools -> [server section] -> System report -> At the end "Summary").

Cordially, janus57

**Comment by AlexL777** [comment] 2017-08-25 10:16
Hello @janus57 

Here is the System Report. 

```---------------------------------System report---------------------------------
-----------------------------generated by PHPBoost-----------------------------
SERVER CONFIGURATION-----------------------------------------------------------
php version			: 5.6.30
dbms version			: MySQL 5.7.15-nmm5-log
gd library			: 1
curl extension		: 1
mbstring extension		: 1
url rewriting			: N/A
apcu cache			: 0
PHPBOOST CONFIGURATION---------------------------------------------------------
phpboost version		: 5.1.dev
server url			: https://phpboost.wpzweinull.ch
site path			: 
default theme			: Base (Version 5.1.0)
default language		: English
default editor			: BBCode
home page			: https://phpboost.wpzweinull.ch/index.php
url rewriting			: 1
apcu cache			: 0
output gzip			: 1
session cookie name		: session
session duration		: 3600
active session duration		: 300
DIRECTORIES AUTHORIZATIONS-----------------------------------------------------
/				: 1
/cache				: 1
/cache/backup			: 1
/cache/syndication		: 1
/cache/tpl			: 1
/cache/css			: 1
/images/avatars			: 1
/images/customization		: 1
/images/group			: 1
/images/maths			: 1
/images/smileys			: 1
/kernel/db			: 1
/lang				: 1
/templates			: 1
/upload				: 1
```

**Comment by janus57** [comment] 2017-08-25 10:19
Hello,

where have you downloaded the V5.1 ?
Because it seem you have download it from github which is a bad idea (every release are package here : https://www.phpboost.com/download/60-phpboost-5-1/478-phpboost-5-1/)

Cordially, janus57

**Comment by AlexL777** [comment] 2017-08-25 12:45
Hm ... very very strange and I've tried everything. The download and its page can not be found. On the vServer in Centos 7 it does not work.

On the managed server there is the directory `/upload` and the path to the file is `/upload/de_de.zip`. But in the front end it is under `/download/download/4` and yet nothing is found.

Even without SEO URLs unfortunately no success.

How can it be.

P.S. I took your download from the support website and installed it freshly. Everything as before.

**Comment by janus57** [comment] 2017-08-25 13:10
Hello,

in the .htaccess do you have ? :
```
# download #
RewriteRule ^download/([\w/_-]*)$ /download/index.php?url=/$1 [L,QSA]
```

Is it possible to know you openssl version (see in phpinfo() and the same section as system report) ?

Cordialement, janus57

**Comment by AlexL777** [comment] 2017-08-25 13:15
Yes, the correct entry in the .htaccess is available.

And in php-info is the `OpenSSL/1.0.2g`

**Comment by janus57** [comment] 2017-08-25 13:23
Hello,

thanks, we will check, we can reproduce but not everytime (different website/hosting).

Cordialement, janus57

**Comment by AlexL777** [comment] 2017-08-25 13:27
OK, thanks!!

**Comment by janus57** [comment] 2017-08-25 15:48
Hello,

if you comment the line :
`ErrorDocument 404 /user/error/404/`
to
`#ErrorDocument 404 /user/error/404/`

in the .htaccess and then you try to download of file, what is the apache error message ?

Something like ? :
> Not Found
> 
> The requested URL /download/download.png/{ID} was not found on this server.

Cordially, janus57

**Comment by AlexL777** [comment] 2017-08-25 17:07
Hello!

Yes, this error is shown to me in the browser. Does that mean something?

Thank you.

**Comment by janus57** [comment] 2017-08-25 17:16
Hello,

yes I have found why you (and other) have "404 not found" when you try to download a file, but we don't find (yet) the origin of the bug.

Can I ask who is your hosting company ?
And if you are and shared hosting ?

Cordially, janus57

**Comment by AlexL777** [comment] 2017-08-25 17:21
Yes, I am at the Webhoster All-inkl in Germany and with Managed Server on Shared Webhosting.

It would work on its own vServer with Hetzner, because there I tried also today and could try again.

**Comment by jbriswalter** [comment] 2017-08-28 04:53
Hi AlexL777

Thank you for this alert!

Here is the fixing commit : https://github.com/PHPBoost/PHPBoost/commit/9f6ac1cdb66b42272803f71fa4eaa8b75a4d6999
When the fix is applied, please go to the Advanced configuration part of the site and validate it again in order to regenerate the .htaccess file.

Next version including this fix (5.1.1) will be released soon (in a few days) if you want to wait.

Best regards
PHPBoost Team

**Comment by jbriswalter** [comment] 2017-08-28 05:07
Hi AlexL777,

You need to apply this commit too before regenerating the .htaccess file : https://github.com/PHPBoost/PHPBoost/commit/d8a95f5cdfcfa28532e2fafd0165142617abf660
Sorry for the inconveniance.

Best regards
PHPBoost Team

**Comment by janus57** [comment] 2017-08-28 12:40
Hello,

@AlexL777 can you test with just this commit : https://github.com/PHPBoost/PHPBoost/commit/9f6ac1cdb66b42272803f71fa4eaa8b75a4d6999

And also what apache version have you (2.2 or 2.4) ?

Cordially, janus57

**Comment by janus57** [comment] 2017-08-28 15:28
Hello,

or more simple car you test to rename the "download.png" image to "download_main.png" under /download folder without touching the PHP and/or the .htaccess ?

Cordialement, janus57

**Comment by AlexL777** [comment] 2017-08-28 17:12
Hello everybody,

Thank you for your efforts and the fix, but unfortunately no success with me. Under http://phpboost.wpzweinull.ch/download/1-test-category/2-sprache/ downloads are recorded and counted. But behind the download it says, "Link not found".

I have uploaded and reloaded the download. But that did not work.

Also I have modified under "Advanced Confuguration" again.

Apache version would be with me 2.4.

Very peculiar, why it does not work.

**Comment by janus57** [comment] 2017-08-28 17:15
Hello,

what have you done exactly ?

Juste use a clean V5.1 and forget the commit and symply rename the download.png image.

Cordialement, janus57

**Comment by AlexL777** [comment] 2017-08-28 17:17
Hello,

I should have a new Clean v. 5.1 from Github or from the official website?

**Comment by janus57** [comment] 2017-08-28 17:20
Hello,

always take from the official website.

And if you rename the image as i said create a new download don't use the example wich will be false/not found/not working (and it's normal).

Cordialement, janus57

**Comment by AlexL777** [comment] 2017-08-28 17:30
Thanks, the installation I'm doing. Give me some time ;)

Then I report again. Then I also take this download module, what you offer here.

I hope that now everything will work.

**Comment by janus57** [comment] 2017-08-28 17:38
Hello,

i hope to because the FollowSymLink is not a good idea i think (Cf : https://www.drupal.org/node/1269780).

And normally in apache 2.4 we don't have the case since it's enable by default in apache config (Cf : https://httpd.apache.org/docs/2.4/en/mod/core.html#options).

Cordially, janus57

**Comment by AlexL777** [comment] 2017-08-28 18:40
Hi,

Unfortunately, I have to give up, the new installation did not lead to success. It is not bad or important that I can offer downloads. Since I can simply disable the respective module.

I was shown an error 404 page behind the download. Without SEO URLs it was said that the link can not be found.

Maybe it is on my managed server. Can be anything.

**Comment by janus57** [comment] 2017-08-28 18:54
Hello,

is it possible to have access to : https://phpboost.wpzweinull.ch ?

Because it's hard to debug like that (and as i can see nothing has benn modified like it was suggested).

Cordialement, janus57

**Comment by AlexL777** [comment] 2017-08-28 19:01
Hi,

As I see, you have already registered with me and I have given you just administrator rights. Now this should be possible with access.

If you still need the FTP access, then tell me please.

Thanks in advance.

**Comment by janus57** [comment] 2017-08-28 19:19
Hello,

ok as i can see you are impacted by an another bug (well murphy law).

This bug is because the "module" try to check if he can see/get the file, and if he cannot then he tell "File not found, the link may be dead." like now.

Note : I PM you on your website.

Cordialement, janus57

**Comment by AlexL777** [comment] 2017-08-28 19:26
OK,

I have your PN just answered and give you the FTP account access. Thank you!

This error message I had today again, even if the file under `/upload` was present.

**Comment by AlexL777** [comment] 2017-08-28 20:07
Thank you very much!

It works now and sorry that I took you a lot of time. I did not get ahead before. Was it now on the module itself and not on the managed server?

Now I can offer great downloads and I am happy :)

**Comment by janus57** [comment] 2017-08-28 20:16
Hello,

you have 2 issue, the first is due to apache configuration regarding "FollowSymLinks" which is resolved by simply renaming the download.png into other name like download_main.png juste to not have a "physical" donwload.png because apache redirect to it (don't know how this work exactly…).

The second issue is that your website cannot try to check himself. For exemple the module try to find "https://phpboost.wpzweinull.ch/download/download_mini.png" but you server give to PHP a HTTP 403 - Not Authorized headers, so for the module the file was probably dead.

P.S. i will reset your module to give you the original one with the fix.

Thank for the debugging, and sorry for the time :(

Cordialement, janus57

**Comment by AlexL777** [comment] 2017-08-28 20:23
Ok, now we've got to figure out what it's all about.

Then I did not introduce new downloads for the first time when I get the fixed module.

I then deal with my PHPBoost website for the first time to set it up.

No problem because of the time, because I want to work with this CMS.

Good work 😄

**Comment by jbriswalter** [comment] 2017-09-08 06:25
Hi,
The problem is  fixed in the next release which will come soon.
Best regards
PHPBoost team

**Closed by jbriswalter** 2017-09-08 06:25 UTC
